### ISSUE TITLE
图片懒加载的本地生成脚本没有包含生成的文章页

### ISSUE THREAD

**Issue by OneCanX** [Lete114/Hexo-Theme-MengD#14]
如图，文章页的图片懒加载未启用，图片img标签中未含有data-img属性
![_5$~4OUUKER{6)0 SJL}M8V](https://user-images.githubusercontent.com/89405361/174925825-290460ac-ed4d-4ee7-8201-83119c5a3b42.jpg)

**Comment by Lete114** [comment]
已修复 [#98e0c73](https://github.com/Lete114/Hexo-Theme-MengD/commit/98e0c7341e3db1f3b2792fa03f952ef96757ca85)
