### ISSUE TITLE
添加 “网站正常运行时间”

### ISSUE THREAD

**Issue by DreamLumine** [Lete114/Hexo-Theme-MengD#15]
代码实现
`<script type="text/javascript">			
    function show_runtime() {
        window.setTimeout("show_runtime()", 1000);
        X = new Date("01/20/2021 21:00:00");
        Y = new Date();
        T = (Y.getTime() - X.getTime());
        M = 24 * 60 * 60 * 1000;
        a = T / M;
        A = Math.floor(a);
        b = (a - A) * 24;
        B = Math.floor(b);
        c = (b - B) * 60;
        C = Math.floor((b - B) * 60);
        D = Math.floor((c - C) * 60);
        runtime_span.innerHTML = "小站于各种崩坏中续存了: " + A + "天" + B + "小时" + C + "分" + D + "秒"
    }
	show_runtime();
</script>`
来源: FaDai's Blog

**Comment by Lete114** [comment]
暂时不考虑此功能
